### ISSUE TITLE
关于编译运行时的流程问题

### ISSUE THREAD

**Issue by prikevs** [NJUST-FishTeam/OnlineJudgeCore#10]
我觉得应该将编译和运行从core中分开，当前的做法是在先沙盒中拷贝进输入输出文件in.in和out.out，然后编译运行。如果用户的code中包含 `#include "in.in"` or `#include "out.out"` ，就能通过CE信息获取测试数据的第一行了。更恰当的流程应该是save code file，编译，save test file，run吧

Thanks.

**Comment by maemual** [comment]
是的，一直以来就是想把程序编译、运行变成参数控制的两个过程。但是后来我发现了 https://github.com/quark-zju/ljudge

**Comment by prikevs** [comment]
Soga，谢谢回复。

**Comment by prikevs** [comment]
对了，还想请教下系统调用的问题，不同语言的调用有什么要注意的吗？比如添加Go, Python，需要禁用的调用有什么规律吗？

**Comment by comzyh** [comment]
我们系统调用采用的是白名单不是黑名单
至于白名单的内容，我猜是试出来的~
@maemual

**Comment by prikevs** [comment]
好，谢谢回复，我研究研究
